name: air101

on:
  push:
    paths:
      - '.github/workflows/air101.yml'
      - 'lua/**'
      - 'luat/**'
      - 'components/**'
      - 'bsp/air101/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: prepare software
      run: |
        sudo apt-get update
        sudo apt-get install git gcc-multilib libc6 libgcc1 libstdc++5 libstdc++6 libsdl-dev p7zip-full -y
        sudo apt-get install libncurses5-dev -y
        sudo add-apt-repository ppa:xmake-io/xmake -y
        sudo apt update
        sudo apt install xmake
        wget -q https://github.com/openLuat/LuatOS/releases/download/v0.0.1/csky-elfabiv2-tools-x86_64-minilibc-20210423.tar.gz
        sudo mkdir /opt/csky-elfabiv2-tools
        sudo tar zxvf csky-elfabiv2-tools-x86_64-minilibc-20210423.tar.gz -C /opt/csky-elfabiv2-tools
        rm csky-elfabiv2-tools-x86_64-minilibc-20210423.tar.gz
    - name: clone 101
      env:
        AIR101REPO: ${{ secrets.AIR101REPO }}
      run: |
        sudo sh -c "curl https://raw.githubusercontent.com/kadwanev/retry/master/retry -o /usr/local/bin/retry && chmod +x /usr/local/bin/retry"
        cd ..
        retry 'git clone --depth=1 --branch=master https://gitee.com/openLuat/luatos-soc-air101 air101'
    - name: make
      run: |
        cd ../air101
        gcc -o tools/xt804/wm_tool tools/xt804/wm_tool.c -pthread
        chmod +x tools/xt804/wm_tool
        xmake
        mkdir ../LuatOS/luatosfw
        mv build/out/*.soc ../LuatOS/luatosfw
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: air101
        path: luatosfw
    - name: report if failure
      if: always()
      env:
        STATUS: ${{ job.status }}
        MQTTADDR: ${{ secrets.MQTTADDR }}
        MQTTPORT: ${{ secrets.MQTTPORT }}
        MQTTTOPIC: ${{ secrets.MQTTTOPIC }}
      run: |
        sudo pip3 install paho_mqtt
        cd tools
        if [ "$STATUS" = "failure" ];then python3 ciNotify.py $MQTTADDR $MQTTPORT $MQTTTOPIC "air101 https://github.com/openLuat/LuatOS/actions/runs/$GITHUB_RUN_ID"; fi
