name: air100st

on:
  push:
    paths:
      - '.github/workflows/air100st.yml'
      - 'lua/**'
      - 'luat/**'
      - 'components/**'
      - 'bsp/air100st/**'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: prepare software
      run: |
        cd ..
        sudo apt-get update
        sudo apt-get install git gcc-multilib libc6 libgcc1 libstdc++5 libstdc++6 libsdl-dev scons -y
        sudo apt-get install libncurses5-dev -y
        sudo pip install requests
        wget -q https://github.com/openLuat/LuatOS/releases/download/v0.0.1/gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2
        sudo tar xjf gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2 -C /opt
        /opt/gcc-arm-none-eabi-6-2017-q2-update/bin/arm-none-eabi-gcc --version
    - name: clone rtt
      run: |
        git clone https://github.com/RT-Thread/rt-thread.git ~/work/action/rt-thread
        cd ~/work/action/rt-thread
        git checkout v4.0.3
    - name: prepare packages
      run: |
        cd bsp/air100st/rtt
        export RTT_EXEC_PATH=/opt/gcc-arm-none-eabi-6-2017-q2-update/bin
        export RTT_ROOT=~/work/action/rt-thread
        echo | scons --menuconfig
        source ~/.env/env.sh
        pkgs --update
    - name: make
      run: |
        cd bsp/air100st/rtt
        export RTT_EXEC_PATH=/opt/gcc-arm-none-eabi-6-2017-q2-update/bin
        export RTT_ROOT=~/work/action/rt-thread
        source ~/.env/env.sh
        scons -j2
        mkdir bin
        mv rtthread.bin bin/
        mv rt-thread.elf bin/
        mv rt-thread.map bin/
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: air100st
        path: bsp/air100st/rtt/bin
